"""SQLAlchemy ORM models for ShadowSensor Phase 3 storage tables."""

from __future__ import annotations

import json
from datetime import datetime
from typing import Any

from sqlalchemy import CheckConstraint, DateTime, Float, ForeignKey, Index, Integer, String, Text, text
from sqlalchemy.orm import Mapped, mapped_column

from storage.database import Base


def _serialize_datetime(value: datetime | None) -> str | None:
    """Convert datetime values to ISO strings for JSON responses."""
    if value is None:
        return None
    return value.isoformat()


class EventRecord(Base):
    """Persisted normalized Sysmon event."""

    __tablename__ = "events"
    __table_args__ = (
        Index("idx_events_timestamp", "timestamp"),
        Index("idx_events_event_type", "event_type_id"),
        Index("idx_events_image", "image"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    event_type_id: Mapped[int] = mapped_column(Integer, nullable=False)
    timestamp: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    pid: Mapped[int | None] = mapped_column(Integer, nullable=True)
    image: Mapped[str | None] = mapped_column(Text, nullable=True)
    raw_json: Mapped[str] = mapped_column(Text, nullable=False)
    ingested_at: Mapped[datetime | None] = mapped_column(
        DateTime,
        server_default=text("(datetime('now','utc'))"),
        nullable=True,
    )

    def __repr__(self) -> str:
        return (
            f"EventRecord(id={self.id}, event_type_id={self.event_type_id}, "
            f"timestamp={self.timestamp!r}, pid={self.pid}, image={self.image!r})"
        )

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-serializable dictionary for API responses."""
        try:
            raw_payload = json.loads(self.raw_json)
        except json.JSONDecodeError:
            raw_payload = self.raw_json

        return {
            "id": self.id,
            "event_type_id": self.event_type_id,
            "timestamp": _serialize_datetime(self.timestamp),
            "pid": self.pid,
            "image": self.image,
            "raw_json": raw_payload,
            "ingested_at": _serialize_datetime(self.ingested_at),
        }


class RuleHitRecord(Base):
    """Persisted rule hit generated by RuleEngine evaluation."""

    __tablename__ = "rule_hits"
    __table_args__ = (
        CheckConstraint("severity IN ('Low','Medium','High','Critical')", name="ck_rule_hits_severity"),
        Index("idx_rule_hits_timestamp", "timestamp"),
        Index("idx_rule_hits_rule_id", "rule_id"),
        Index("idx_rule_hits_severity", "severity"),
        Index("idx_rule_hits_event_fk", "event_fk"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    event_fk: Mapped[int | None] = mapped_column(
        Integer,
        ForeignKey("events.id", ondelete="SET NULL"),
        nullable=True,
    )
    rule_id: Mapped[str] = mapped_column(Text, nullable=False)
    rule_name: Mapped[str] = mapped_column(Text, nullable=False)
    severity: Mapped[str] = mapped_column(String, nullable=False)
    mitre_technique: Mapped[str | None] = mapped_column(Text, nullable=True)
    mitre_tactic: Mapped[str | None] = mapped_column(Text, nullable=True)
    matched_fields: Mapped[str | None] = mapped_column(Text, nullable=True)
    timestamp: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    created_at: Mapped[datetime | None] = mapped_column(
        DateTime,
        server_default=text("(datetime('now','utc'))"),
        nullable=True,
    )

    def __repr__(self) -> str:
        return (
            f"RuleHitRecord(id={self.id}, rule_id={self.rule_id!r}, severity={self.severity!r}, "
            f"event_fk={self.event_fk}, timestamp={self.timestamp!r})"
        )


class AlertRecord(Base):
    """Persisted alert record generated from a rule hit."""

    __tablename__ = "alerts"
    __table_args__ = (
        CheckConstraint("severity IN ('Low','Medium','High','Critical')", name="ck_alerts_severity"),
        CheckConstraint("status IN ('open','acknowledged','resolved')", name="ck_alerts_status"),
        Index("idx_alerts_timestamp", "timestamp"),
        Index("idx_alerts_severity", "severity"),
        Index("idx_alerts_status", "status"),
        Index("idx_alerts_rule_id", "rule_id"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    rule_hit_fk: Mapped[int | None] = mapped_column(
        Integer,
        ForeignKey("rule_hits.id", ondelete="SET NULL"),
        nullable=True,
    )
    event_fk: Mapped[int | None] = mapped_column(
        Integer,
        ForeignKey("events.id", ondelete="SET NULL"),
        nullable=True,
    )
    rule_id: Mapped[str] = mapped_column(Text, nullable=False)
    rule_name: Mapped[str] = mapped_column(Text, nullable=False)
    severity: Mapped[str] = mapped_column(String, nullable=False)
    mitre_technique: Mapped[str | None] = mapped_column(Text, nullable=True)
    mitre_tactic: Mapped[str | None] = mapped_column(Text, nullable=True)
    process_image: Mapped[str | None] = mapped_column(Text, nullable=True)
    process_pid: Mapped[int | None] = mapped_column(Integer, nullable=True)
    command_line: Mapped[str | None] = mapped_column(Text, nullable=True)
    parent_image: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[str] = mapped_column(String, nullable=False, server_default=text("'open'"))
    suspected_families: Mapped[str | None] = mapped_column(Text, nullable=True, default=None)
    timestamp: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    created_at: Mapped[datetime | None] = mapped_column(
        DateTime,
        server_default=text("(datetime('now','utc'))"),
        nullable=True,
    )

    def __repr__(self) -> str:
        return (
            f"AlertRecord(id={self.id}, rule_id={self.rule_id!r}, severity={self.severity!r}, "
            f"status={self.status!r}, event_fk={self.event_fk}, rule_hit_fk={self.rule_hit_fk})"
        )

    def to_dict(self) -> dict[str, Any]:
        """Return all alert fields as a JSON-serializable dictionary."""
        return {
            "id": self.id,
            "rule_hit_fk": self.rule_hit_fk,
            "event_fk": self.event_fk,
            "rule_id": self.rule_id,
            "rule_name": self.rule_name,
            "severity": self.severity,
            "mitre_technique": self.mitre_technique,
            "mitre_tactic": self.mitre_tactic,
            "process_image": self.process_image,
            "process_pid": self.process_pid,
            "command_line": self.command_line,
            "parent_image": self.parent_image,
            "status": self.status,
            "suspected_families": self.suspected_families,
            "timestamp": _serialize_datetime(self.timestamp),
            "created_at": _serialize_datetime(self.created_at),
        }


class ModelScoreRecord(Base):
    """Persisted model score record reserved for Phase 6B population."""

    __tablename__ = "model_scores"
    __table_args__ = (
        CheckConstraint(
            "model_type IN ('isolation_forest','random_forest')",
            name="ck_model_scores_model_type",
        ),
        CheckConstraint("score >= 0.0 AND score <= 1.0", name="ck_model_scores_score"),
        Index("idx_model_scores_timestamp", "timestamp"),
        Index("idx_model_scores_event_fk", "event_fk"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    event_fk: Mapped[int | None] = mapped_column(
        Integer,
        ForeignKey("events.id", ondelete="SET NULL"),
        nullable=True,
    )
    model_type: Mapped[str] = mapped_column(String, nullable=False)
    score: Mapped[float] = mapped_column(Float, nullable=False)
    timestamp: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    created_at: Mapped[datetime | None] = mapped_column(
        DateTime,
        server_default=text("(datetime('now','utc'))"),
        nullable=True,
    )

    def __repr__(self) -> str:
        return (
            f"ModelScoreRecord(id={self.id}, model_type={self.model_type!r}, "
            f"score={self.score}, event_fk={self.event_fk}, timestamp={self.timestamp!r})"
        )
